;;; gen-tables.el --- Generate org-syntax character and entity tables  -*- lexical-binding: t; -*-

;; Licensed under MIT OR Apache-2.0.
;;
;; Usage (from the repository root):
;;
;;   emacs -Q --batch -l tools/gen-tables.el
;;
;; Writes crates/org-syntax/src/tables/chars.rs and entities.rs.  The
;; character classes are those Org's parser sees in an `org-mode' buffer:
;; syntax classes from `org-mode-syntax-table', regexp character classes
;; and the "line breakable" category used by radio target matching.
;; Entities are the names from `org-entities', which decide what the
;; parser recognizes as an entity.

(require 'org)
(require 'org-entities)

(defconst gen-syntax-codes
  '((?\s . 0) (?w . 1) (?_ . 2) (?. . 3) (?\( . 4) (?\) . 5) (?\" . 6)
    (?\\ . 7) (?$ . 8) (?' . 9) (?< . 10) (?> . 11) (?! . 12) (?| . 13) (?@ . 14))
  "Map from `char-syntax' results to small integers.")

(defun gen-bits (c)
  "Return the class bits for character C in the current buffer."
  (let ((s (string c)))
    (logior (cdr (assq (char-syntax c) gen-syntax-codes))
            (if (string-match-p "[[:alnum:]]" s) #x10 0)
            (if (string-match-p "[[:alpha:]]" s) #x20 0)
            (if (string-match-p "[[:punct:]]" s) #x40 0)
            (if (string-match-p "[[:blank:]]" s) #x80 0)
            (if (aref (char-category-set c) ?|) #x100 0)
            (if (string-match-p "[[:upper:]]" s) #x200 0)
            (if (string-match-p "[[:lower:]]" s) #x400 0)
            (let ((cats (char-category-set c)))
              (logior (if (aref cats ?^) #x800 0)
                      (if (aref cats ?C) #x1000 0)
                      (if (aref cats ?H) #x2000 0)
                      (if (aref cats ?K) #x4000 0)
                      (if (equal (category-set-mnemonics cats) "") #x8000 0))))))

(defun gen-chars (file)
  (with-temp-buffer
    (org-mode)
    (let ((case-fold-search nil)
          (ranges nil) (start 0) (bits (gen-bits 0)))
      (let ((c 1))
        (while (<= c #x10FFFF)
          (unless (and (>= c #xD800) (<= c #xDFFF))
            (let ((b (gen-bits c)))
              (unless (= b bits)
                (push (list start (1- c) bits) ranges)
                (setq start c bits b))))
          (setq c (1+ c))))
      (push (list start #x10FFFF bits) ranges)
      (setq ranges (nreverse ranges))
      (with-temp-file file
        (insert "// @generated by tools/gen-tables.el from Emacs " emacs-version
                " and Org " (org-version) ". Do not edit.\n"
                "//\n"
                "// Each entry is (first, last, bits). Bits 0..3 hold the syntax class\n"
                "// (0 whitespace, 1 word, 2 symbol, 3 punctuation, 4 open, 5 close,\n"
                "// 6 string, 7 escape, 8 paired delimiter, 9 expression prefix,\n"
                "// 10 comment start, 11 comment end, 12 generic comment,\n"
                "// 13 generic string, 14 inherit). Higher bits: 0x10 [:alnum:],\n"
                "// 0x20 [:alpha:], 0x40 [:punct:], 0x80 [:blank:],\n"
                "// 0x100 line-breakable category, 0x200 [:upper:], 0x400 [:lower:],\n"
                "// categories 0x800 ^ (combining), 0x1000 C, 0x2000 H, 0x4000 K,\n"
                "// 0x8000 no categories at all.\n\n"
                (format "pub(crate) static CHAR_CLASSES: [(u32, u32, u16); %d] = [\n" (length ranges)))
        (dolist (r ranges)
          (insert (format "    (0x%X, 0x%X, 0x%X),\n" (nth 0 r) (nth 1 r) (nth 2 r))))
        (insert "];\n")))))

(defun gen-scripts (file)
  "Write `char-script-table' as ranges of script numbers."
  (let ((ids nil) (next 0) (ranges nil) (start 0) (cur nil))
    (let ((c 0))
      (while (<= c #x10FFFF)
        (unless (and (>= c #xD800) (<= c #xDFFF))
          (let* ((sym (aref char-script-table c))
                 (id (or (cdr (assq sym ids))
                         (progn (push (cons sym next) ids) (setq next (1+ next)) (1- next)))))
            (unless (eql id cur)
              (when cur (push (list start (1- c) cur) ranges))
              (setq start c cur id))))
        (setq c (1+ c))))
    (push (list start #x10FFFF cur) ranges)
    (with-temp-file file
      (insert "// @generated by tools/gen-tables.el from Emacs " emacs-version ". Do not edit.\n"
              "//\n"
              "// `char-script-table' as (first, last, script) ranges. Script numbers\n"
              "// are arbitrary; only equality matters (word boundaries).\n\n"
              (format "pub(crate) static SCRIPTS: [(u32, u32, u8); %d] = [\n" (length ranges)))
      (dolist (r (nreverse ranges))
        (insert (format "    (0x%X, 0x%X, %d),\n" (nth 0 r) (nth 1 r) (nth 2 r))))
      (insert "];\n"))))

(defun gen-rust-string (s)
  (setq s (if (or (null s) (stringp s)) s (format "%s" s)))
  (if (null s) "\"\""
    (concat "\""
            (mapconcat (lambda (c)
                         (cond ((eq c ?\") "\\\"")
                               ((eq c ?\\) "\\\\")
                               ((< c 32) (format "\\u{%x}" c))
                               (t (string c))))
                       s "")
            "\"")))

(defun gen-entities (file)
  (let ((entries (seq-filter #'consp org-entities)))
    (setq entries (sort (copy-sequence entries) (lambda (a b) (string< (car a) (car b)))))
    (with-temp-file file
      (insert "// @generated by tools/gen-tables.el from Org " (org-version) ". Do not edit.\n"
              "//\n"
              "// Entity names recognized by Org, sorted, with their renderings:\n"
              "// (name, latex, latex_math_p, html, ascii, latin1, utf8).\n\n"
              (format "pub(crate) static ENTITIES: [(&str, &str, bool, &str, &str, &str, &str); %d] = [\n"
                      (length entries)))
      (dolist (e entries)
        (insert (format "    (%s, %s, %s, %s, %s, %s, %s),\n"
                        (gen-rust-string (nth 0 e)) (gen-rust-string (nth 1 e))
                        (if (nth 2 e) "true" "false")
                        (gen-rust-string (nth 3 e)) (gen-rust-string (nth 4 e))
                        (gen-rust-string (nth 5 e)) (gen-rust-string (nth 6 e)))))
      (insert "];\n"))))

(defun gen-case (file)
  "Write characters whose `upcase' or `downcase' string differs from them,
and the case-folding canon table."
  (require 'case-table)
  (let (up down canon)
    (let ((c 0))
      (while (<= c #x10FFFF)
        (unless (and (>= c #xD800) (<= c #xDFFF))
          (let* ((s (string c)) (u (upcase s)) (d (downcase s)))
            (unless (equal u s) (push (cons c u) up))
            (unless (equal d s) (push (cons c d) down))))
        (setq c (1+ c))))
    (let ((table (case-table-get-table (standard-case-table) 'canon))
          (c 0))
      (while (<= c #x10FFFF)
        (let ((k (aref table c)))
          (when (and k (/= k c)) (push (cons c k) canon)))
        (setq c (1+ c))))
    (with-temp-file file
      (insert "// @generated by tools/gen-tables.el from Emacs " emacs-version ". Do not edit.\n"
              "//\n"
              "// Emacs's `upcase' and `downcase' on one-character strings, for the\n"
              "// characters they change. Emacs differs from Unicode's default case\n"
              "// mapping in places (for example it leaves the dotless i unchanged).\n"
              "// CANON is the canonical-equivalence table `case-fold-search' matches\n"
              "// through, for the characters it does not map to themselves.\n\n")
      (insert (format "pub(crate) static CANON: [(char, char); %d] = [\n" (length canon)))
      (dolist (e (nreverse canon))
        (insert (format "    ('\\u{%X}', '\\u{%X}'),\n" (car e) (cdr e))))
      (insert "];\n\n")
      (dolist (pair (list (cons "UPCASE" (nreverse up)) (cons "DOWNCASE" (nreverse down))))
        (insert (format "pub(crate) static %s: [(char, &str); %d] = [\n" (car pair) (length (cdr pair))))
        (dolist (e (cdr pair))
          (insert (format "    ('\\u{%X}', %s),\n" (car e) (gen-rust-string (cdr e)))))
        (insert "];\n\n")))))

(let ((dir (expand-file-name "crates/org-syntax/src/tables/")))
  (make-directory dir t)
  (gen-chars (expand-file-name "chars.rs" dir))
  (gen-entities (expand-file-name "entities.rs" dir))
  (gen-case (expand-file-name "case.rs" dir))
  (gen-scripts (expand-file-name "scripts.rs" dir))
  (message "Wrote %s" dir))

;;; gen-tables.el ends here
