#!/usr/bin/env python3
"""The Book's page of what the LaTeX view leaves as source (T2.7h.13),
from a report of `kalem latex-coverage` over the arXiv sample (the arXiv
workflow's summary, or a local run).

Usage: tools/latex-limitations.py REPORT.md RUN DATE > book/part-2/latex-limitations.org

RUN and DATE name the measurement (`run 36`, `2026-10-03`)."""

import re
import sys

TOP = 40
MESSAGES = 20


def tables(text):
    """The report's tables by the line before each: rows of cells."""
    out = {}
    title = None
    rows = None
    for line in text.splitlines():
        if line.startswith("|"):
            if rows is None:
                rows = []
                out[title] = rows
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if all(set(c) <= set("-:") for c in cells):
                continue
            rows.append(cells)
        else:
            rows = None
            if line.strip():
                title = line.strip()
    return out


def org(s):
    """A cell's text for an Org table: no bars, code as verbatim."""
    s = s.replace("\\|", "/").replace("|", "/")
    s = re.sub(r"`([^`]*)`", lambda m: "=" + m.group(1) + "=", s)
    if len(s) > 70:
        s = s[:69] + "…"
    return s


def verbatim(s):
    """Source text as Org verbatim, with a marker it does not contain."""
    s = org(s).strip("=")
    for mark in "=~":
        if mark not in s:
            return f"{mark}{s}{mark}"
    return s


def main():
    path, run, date = sys.argv[1], sys.argv[2], sys.argv[3]
    text = open(path, encoding="utf-8").read()
    t = tables(text)
    summary = next((l for l in text.splitlines() if " papers, " in l), "")
    fields = next(rows for title, rows in t.items() if rows and rows[0][:2] == ["field", "papers"])
    names = next(rows for title, rows in t.items() if title and "names showing the most source" in title)
    messages = next(
        (rows for title, rows in t.items() if title and "renderer messages" in title), [["message"]]
    )
    print("#+TITLE: LaTeX: what shows as source")
    print()
    print(
        "What Kalem's view of LaTeX leaves as source, measured on the arXiv sample of "
        "the coverage study (decision D30, =kalem latex-coverage=, the arXiv workflow), "
        f"{run}, {date}. This page is generated by =tools/latex-limitations.py= from "
        "the report; regenerate it with each measurement rather than editing it."
    )
    print()
    m = re.match(r"(\d+) papers, (\d+) files, (\d+) KB", summary)
    if m:
        print(
            f"The sample: {m.group(1)} papers, {m.group(2)} files, {int(m.group(3)):,} KB of body text "
            "(200 papers per field submitted in 2024, five fields, five categories each)."
        )
        print()
    print("* By field")
    print()
    print("| Field | Papers | Files | Body KB | Shown as source | Formulas | Formulas TeX typesets |")
    print("|-------+--------+-------+---------+-----------------+----------+-----------------------|")
    for r in fields[1:]:
        kb = f"{int(r[3]):,}" if r[3].isdigit() else r[3]
        print("| " + " | ".join([r[0].replace("-", " "), r[1], r[2], kb] + r[4:]) + " |")
    print()
    print(
        "A construct shows as source when the view neither renders it nor knows it prints "
        "nothing: its command name and arguments stay as written, dimmed, never hidden or "
        "guessed (the standard modes' third rule). The formulas the math renderer cannot "
        "read are typeset by TeX when it is installed; without TeX they show as source too."
    )
    print()
    target = next(
        (rows for title, rows in t.items() if title and title.startswith("Papers at the target")), None
    )
    worst = next(
        (rows for title, rows in t.items() if title and "papers showing the most source" in title), None
    )
    if target:
        print("* By paper")
        print()
        print(
            "The papers whose body shows less than 3% as source, the target of D30 for "
            "each paper (papers with less than 2 KB of body left out):"
        )
        print()
        print("| Field | Papers | At the target | Share |")
        print("|-------+--------+---------------+-------|")
        for r in target[1:]:
            print("| " + " | ".join([r[0].replace("-", " ")] + r[1:]) + " |")
        print()
        if worst and len(worst) > 1:
            print("The papers that show the most source, with the share of their body:")
            print()
            print("| Paper | Field | Body KB | Shown as source | Formulas TeX typesets |")
            print("|-------+-------+---------+-----------------+-----------------------|")
            for r in worst[1:21]:
                print("| " + " | ".join([r[0], r[1].replace("-", " ")] + r[2:]) + " |")
            print()
    print("* The constructs that show the most source")
    print()
    print(
        "The names behind the source, by the bytes they leave, with the papers that use "
        "them. A name in one or two papers is mostly a paper's own macro whose definition "
        "the view cannot follow (a loop, a picture drawn in TeX, a package read nowhere "
        "else); a name in many is a construct the view should learn."
    )
    print()
    print("| Name | Source KB | Share of source | Papers | Example |")
    print("|------+-----------+-----------------+--------+---------|")
    for r in names[1 : TOP + 1]:
        if len(r) < 5:
            continue
        print(f"| {verbatim(r[0])} | {r[1]} | {r[2]} | {r[3]} | {verbatim(r[4])} |")
    print()
    own = sum(1 for r in names[1:] if len(r) >= 4 and r[3].isdigit() and int(r[3]) <= 2)
    print(
        f"Of the {len(names) - 1} names that leave the most source, {own} are in one or two papers."
    )
    print()
    if len(messages) > 1:
        print("* Formulas the math renderer cannot read")
        print()
        print("Why the formulas TeX typesets fail in the math renderer, by bytes:")
        print()
        print("| Message | KB | Papers | Example |")
        print("|---------+----+--------+---------|")
        for r in messages[1 : MESSAGES + 1]:
            if len(r) < 4:
                continue
            print(f"| {org(r[0])} | {r[1]} | {r[2]} | {verbatim(r[3])} |")
        print()


if __name__ == "__main__":
    main()
