#!/usr/bin/env python3
"""The math renderer's formula corpus (T2.7h.34):
tests/corpus/math/katex-corpus.txt, a thousand formulas KaTeX renders,
taken from two openly licensed books that tests/corpus/fetch-latex.sh
fetches, as Kalem's view reads them.

Usage: tools/math-corpus.py [CACHE]   (CACHE defaults to .cache/latex)

Needs the `formulas` example built (cargo build --release -p kalem-core
--example formulas) and node with the katex package (NODE_PATH). Prints
how the renderer and KaTeX agree over every formula of the books, then
writes the corpus."""

import hashlib
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOOKS = {"open-logic": "OpenLogicProject_OpenLogic", "hott": "HoTT_book"}
PER_BOOK = 500


def main():
    cache = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, ".cache", "latex")
    files = []
    for d in BOOKS.values():
        for dirpath, _, names in os.walk(os.path.join(cache, d)):
            files += [os.path.join(dirpath, n) for n in names if n.endswith(".tex")]
    exe = os.path.join(ROOT, "target", "release", "examples", "formulas")
    found = subprocess.run([exe] + sorted(files), stdout=subprocess.PIPE, check=True).stdout
    judged = subprocess.run(
        ["node", os.path.join(ROOT, "tools", "katex-check.js")],
        input=found,
        stdout=subprocess.PIPE,
        check=True,
    ).stdout.decode()
    version = json.loads(
        subprocess.run(
            ["node", "-e", "console.log(JSON.stringify(require('katex/package.json').version))"],
            stdout=subprocess.PIPE,
            check=True,
        ).stdout
    )
    both = [0, 0, 0, 0]
    seen = set()
    pools = {k: [] for k in BOOKS}
    for line in judged.splitlines():
        d = json.loads(line)
        k, r = d["katex"] == "ok", d["ratex"] == "ok"
        both[2 * k + r] += 1
        if k and not r:
            print("renderer fails where KaTeX does not:", d["file"], d["ratex"], repr(d["tex"][:120]))
        t = d["tex"].strip("\n")
        if not k or not t.strip() or t in seen or len(t) > 600:
            continue
        if any(x.startswith("%%") for x in t.split("\n")):
            continue
        seen.add(t)
        book = next(b for b, d2 in BOOKS.items() if d2 in d["file"])
        rel = d["file"].split(BOOKS[book] + os.sep, 1)[1]
        pools[book].append((hashlib.sha256(t.encode()).hexdigest(), rel, d["display"], t))
    print(
        f"both read {both[3]}, only KaTeX {both[2]}, only the renderer {both[1]}, neither {both[0]}"
    )
    out = []
    for book in BOOKS:
        chosen = sorted(pools[book])[:PER_BOOK]
        out += [(book,) + c[1:] for c in sorted(chosen, key=lambda c: (c[1], c[0]))]
    with open(os.path.join(ROOT, "tests", "corpus", "math", "katex-corpus.txt"), "w") as f:
        f.write(
            f"""% A thousand formulas KaTeX ({"katex@" + version}) renders, for the math renderer to read
% too (T2.7h.34): 500 from the Open Logic Project (CC BY 4.0,
% https://openlogicproject.org) and 500 from the HoTT book (CC BY-SA 3.0,
% https://homotopytypetheory.org/book), as Kalem's view reads them out of
% their sources, chosen by the hash of their text among those without the
% books' own macros. This file is CC BY-SA 3.0, as the HoTT book is.
% Regenerated by tools/math-corpus.py. Each formula follows a line
% "%% SOURCE FILE inline|display".
"""
        )
        for book, rel, display, t in out:
            f.write(f"%% {book} {rel} {'display' if display else 'inline'}\n{t}\n")


if __name__ == "__main__":
    main()
